# version: 2.1

# orbs:
#   aws-ecr: circleci/aws-ecr@6.2.0
#   aws-ecs: circleci/aws-ecs@0.0.11

# workflows:
# # Log into AWS, build and push image to Amazon ECR
#   build_and_push_image:
#     jobs:
#       - aws-ecr/build-and-push-image:
#           account-url: AWS_ECR_ACCOUNT_URL
#           aws-access-key-id: AWS_ACCESS_KEY_ID
#           aws-secret-access-key: AWS_SECRET_ACCESS_KEY
#           create-repo: true
#           # Name of dockerfile to use. Defaults to Dockerfile.
#           dockerfile: Dockerfile
#           # AWS_REGION_ENV_VAR_NAME
#           region: AWS_DEFAULT_REGION
#           # myECRRepository
#           repo: '${MY_APP_PREFIX}'
#           # myECRRepoTag
#           tag: "$CIRCLE_SHA1"
#       - aws-ecs/deploy-service-update:
#           requires:
#             - aws-ecr/build-and-push-image
#           aws-region: AWS_DEFAULT_REGION
#           family: '${MY_APP_PREFIX}-service'
#           cluster-name: '${MY_APP_PREFIX}-cluster'
#           container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'

version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          context: myContext
          create-repo: true
          dockerfile: Dockerfile
          executor: aws-ecr/default
          extra-build-args: '--compress'
          new-profile-name: newProfileName
          no-output-timeout: 20m
          path: pathToMyDockerfile
          platform: linux/amd64
          profile-name: myProfileName
          public-registry: false
          push-image: true
          region: AWS_DEFAULT_REGION
          # registry-id: AWS_ECR_REGISTRY_ID
          repo: testrepo
          repo-scan-on-push: true
          # role-arn: 'arn:aws:iam::123456789012:role/testing'
          skip-when-tags-exist: false
          source-profile: sourceProfileName
          tag: 'latest,myECRRepoTag'

